config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "journals#index"

  resources :books, only: [:index, :show] do
    member do
      get :reserve
    end
  end

  resources :journals, only: [:index, :show] do
    member do
      get :reserve
    end
  end

  resources :reservations, only: [:index] do
    member do
      post :approve
      post :reject
    end
  end

  resources :users, only: [:index, :show]

  resources :loans, only: [:index] do
    member do
      post :return
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book, optional: true
  belongs_to :journal, optional: true

  validates :expires_at, presence: true
  enum :status, %i[pending approved]

  def reservation_expired?
    expires_at < Time.current
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:approve, :reject]

  def index
    @reservations = current_user.library_personnel? ? Reservation.all.where(status: 'pending') : current_user.reservations

    respond_to do |format|
      format.html # renders the default HTML view
      format.json { render json: @reservations }
      format.xml  { render xml: @reservations }
    end
  end

  def approve
    @reservation.update(status: 'approved')
    Loan.create(user: @reservation.user, book: @reservation.book, journal: @reservation.journal, due_date: 2.weeks.from_now)

    respond_to do |format|
      format.html { redirect_to reservations_path, notice: 'Reservation approved' }
      format.json { render json: @reservation, status: :ok }
      format.xml  { render xml: @reservation, status: :ok }
    end
  end 

  def reject
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_path, notice: 'Reservation rejected' }
      format.json { render json: @reservation, status: :ok }
      format.xml  { render xml: @reservation, status: :ok }
    end
  end
  
  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/views/reservations/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="h2">Current Reservations</h1>
</div>

<% if @reservations.present? %>
  <div class="table-responsive mt-5">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col">
            Item
          </th>
          <th scope="col">
            Reservation Status
          </th>
          <th scope="col">
            Expiration Time
          </th>
          <% if current_user.library_personnel? %>
            <th scope="col">
              Reserved By
            </th>
            <th scope="col">
              Manage
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <th scope="row">
              <%= link_to (reservation.book ? reservation.book.title : reservation.journal.title), reservation.book || reservation.journal, class: 'text-primary' %>
            </th>
            <td>
              <%= reservation.status %>
            </td>
            <td>
              <% if reservation.status != 'pending' %>
                ---
              <% elsif reservation.reservation_expired? %>
                <span class="text-danger">Reservation Expired</span>
              <% else %>
                <%= distance_of_time_in_words(reservation.expires_at, Time.current) %>
              <% end %>
            </td>
            <% if current_user.library_personnel? %>
              <td>
                <%= reservation.user.name %>
              </td>
              <td class="d-flex gap-2">
                <%= button_to 'Approve', approve_reservation_path(reservation), method: :post, class: 'btn text-success p-0' %>
                <%= button_to 'Reject', reject_reservation_path(reservation), method: :post, class: 'btn text-danger p-0' %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="mt-5">No current reservations available</div>
<% end %>