config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "journals#index"

  resources :books, only: [:index, :show] do
    member do
      get :reserve
    end
  end

  resources :journals, only: [:index, :show] do
    member do
      get :reserve
    end
  end

  resources :reservations, only: [:index] do
    member do
      post :approve
      post :reject
    end
  end

  resources :users, only: [:index, :show]

  resources :loans, only: [:index] do
    member do
      post :return
    end
  end
end

app/models/journal.rb
class Journal < ApplicationRecord
  validates :title, :volume, :issue, :language, :publish_year, presence: true

  scope :search, ->(query) { where("title ILIKE ?", "%#{query}%") }
  scope :by_category, ->(category) { where(category: category) }

  enum :category, %i[
    Academic
    Historic
    Popular
  ]

  has_one :reservation, dependent: :destroy

  def available?
    reservation.nil? || reservation.reservation_expired?
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!, only: [:reserve]
  before_action :set_journal, only: [:show, :reserve]
  def index
    @journals = Journal.all
    @journals = @journals.search(params[:search]) if params[:search].present?
    @journals = @journals.by_category(params[:category]) if params[:category].present?
    @current_category = params[:category]
    @query = params[:search]

    respond_to do |format|
      format.html # renders the default HTML view
      format.json { render json: @journals }
      format.xml  { render xml: @journals }
    end
  end

  def show
    respond_to do |format|
      format.html # renders the default HTML view
      format.json { render json: @journal }
      format.xml  { render xml: @journal }
    end
  end

  def reserve
    @journal.reservation.destroy if @journal.reservation&.reservation_expired?
    if @journal.available? && current_user.reservations.create(journal: @journal, expires_at: 2.hours.from_now, status: 'pending')
      respond_to do |format|  
        format.html { redirect_to journals_path, notice: "Journal reserved successfully" }
        format.json { render json: @journal, status: :created }
        format.xml  { render xml: @journal, status: :created }
      end
    else
      respond_to do |format|
        format.html { redirect_to journals_path, alert: "Failed to reserve journal" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
        format.xml  { render xml: @journal.errors, status: :unprocessable_entity }  
      end
    end
  end

  private

  def set_journal
    @journal = Journal.find(params[:id])
  end
end

app/views/journals/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="h2">Journal Collection</h1>
</div>

<%= form_with url: journals_path, method: :get, class: "my-4 w-100 d-flex flex-column align-items-center flex-md-row justify-content-center gap-3" do |form| %>
  <%= form.text_field :search, placeholder: "Search by title", class: "form-control", value: @query %>
  <%= form.select :category, options_for_select(Journal.categories.keys.map { |category| [category.humanize, category] }, @current_category), {prompt: "Choose a category"}, class: "form-select" %>
  <%= form.submit "Search Journals", class: "btn btn-success" %>
<% end %>

<% if @journals.present? %>
  <div class="table-responsive mt-5">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col">
            Journal Title
          </th>
          <th scope="col">
            Volume Number
          </th>
          <th scope="col">
            Issue Number
          </th>
          <th scope="col">
            Journal Category
          </th>
          <th scope="col">
            Available Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @journals.each do |journal| %>
          <tr>
            <th scope="row">
              <%= link_to journal.title, journal, class: 'text-primary' %>
            </th>
            <td>
              <%= journal.volume %>
            </td>
            <td>
              <%= journal.issue %>
            </td>
            <td>
              <%= journal.category.humanize %>
            </td>
            <td>
              <% if journal.available? %>
                <%= link_to 'Reserve Now', reserve_journal_path(journal), class: 'text-primary' %>
              <% else %>
                Currently Reserved
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="mt-5">No journals found in the collection</div>
<% end %>

app/views/journals/show.html.erb
<div class="mt-4 d-flex justify-content-between align-items-center">
  <h1 class="h2">Journal</h1>
  <div class="mt-2">
    <% if @journal.available? %>
      <%= link_to "Reserve", reserve_journal_path(@journal), class: "btn btn-primary" %>
    <% else %>
      <span class="text-danger">Not available</span>
      <% if @journal.reservation.present? %>
        <div class="mt-2">Reserved by: <%= @journal.reservation.user.name %></div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="mt-4">
  <h2 class="h5">Title</h2>
  <p class="text-muted"><%= @journal.title %></p>
</div>

<div class="mt-4">
  <h2 class="h5">Volume</h2>
  <p class="text-muted"><%= @journal.volume %></p>
</div>

<div class="mt-4">
  <h2 class="h5">Issue</h2>
  <p class="text-muted"><%= @journal.issue %></p>
</div>

<div class="mt-4">
  <h2 class="h5">Publish Year</h2>
  <p class="text-muted"><%= @journal.publish_year %></p>
</div>

<div class="mt-4">
  <h2 class="h5">Category</h2>
  <p class="text-muted"><%= @journal.category %></p>
</div>

<div class="mt-4">
  <h2 class="h5">Description</h2>
  <p class="text-muted"><%= @journal.description || "No description available" %></p>
</div>